-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 23:09:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema review_archive_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `review_archive_api` DEFAULT CHARACTER SET utf8mb4 ;
USE `review_archive_api` ;

SET CHARSET utf8mb4;

-- -----------------------------------------------------
-- Table `review_archive_api`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_archive_api`.`content`(
  `content_id` INT NOT NULL AUTO_INCREMENT COMMENT 'コンテンツID',
  `title` VARCHAR(255) NOT NULL COMMENT 'タイトル名',
  `user_id` VARCHAR(255) NOT NULL COMMENT 'ユーザーID',
  `before_code` TEXT  COMMENT '修正前コード',
  `after_code` TEXT  COMMENT '修正後コード',
  `review` TEXT  COMMENT 'レビュー内容',
  `memo` TEXT  COMMENT 'メモ',
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB
COMMENT = 'コンテンツ';


-- -----------------------------------------------------
-- Table `review_archive_api`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_archive_api`.`keyword` (
  `id` INT NOT NULL COMMENT 'コンテンツID',
  `contentKeyword` VARCHAR(255) NOT NULL COMMENT 'キーワード',
  PRIMARY KEY (`id`, `contentKeyword`),
  CONSTRAINT `fk_content_keyword`
    FOREIGN KEY (`id`)
    REFERENCES `review_archive_api`.`content` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION) 
ENGINE=InnoDB
COMMENT = 'キーワード';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
