version: "3"

services:
  # MySQLサービス
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "review-archive"
      MYSQL_DATABASE: "review_archive_api"
      CREDENTIALS: /key.json
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./backend/db/init:/docker-entrypoint-initdb.d
      - ./backend/db-data:/var/lib/mysql
      - ${CREDENTIALS}:/key.json:ro

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "review-archive"
    ports:
      - "127.0.0.1:4001:80"
    links:
      - mysql

  frontend:
    image: node:latest
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start # command: bash -c "npm install && npm install firebase && npm start"
    ports:
      - "3000:3000"

  backend:
    image: golang:latest
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run ./cmd/main.go # bash -c "go get -u firebase.google.com/go && go get -u google.golang.org/api/option && go run ./cmd/main.go"
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: review-archive
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: review_archive_api
    depends_on:
        - mysql
volumes:
  db-data:
    driver: local
